---
title: "Plots About NY Restaurant Inspectations"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data("rest_inspec")
```


Column {data-width=500}
-----------------------------------------------------------------------

###  Grade Date

Using *LINEPLOT* to indicate the **number** of restaurants received the grade in the month.

```{r}
rest_inspec %>% 
  select(grade_date) %>% 
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[as.numeric(month)]) %>% 
  group_by(year, month) %>% 
  summarize(number = n()) %>% 
  plot_ly(x = ~month, y = ~number, type = "scatter",
          mode = "lines", color = ~year) %>% 
  layout(
    title = "Grade Date",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Number of Restaurants")
  )
```

Column {data-width=500}
-----------------------------------------------------------------------

### Numbers of Top 15 Cuisine Restaurants in Manhattan

Using a *BARPLOT* to indicate the **number** of top 15 restaurants in *Manhattan*.

```{r}
rest_inspec %>% 
  select(boro, cuisine_description) %>% 
  filter(boro == "MANHATTAN") %>%
  count(cuisine_description, sort = TRUE) %>% 
  top_n(15) %>% 
  mutate(cuisine_description = 
           recode(cuisine_description, "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin (CDPRSCA)")) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, 
          color = ~cuisine_description, type = "bar") %>% 
  layout(
    title = "Numbers of Top 15 Cuisine Restaurants in Manhattan",
    xaxis = list(title = "Cuisine Description"),
    yaxis = list(title = "Number")
  )
```

### Distribution of Scores in Different Boroughs

Using a *BOXPLOT* to indicate the **score** distribution in all restaurants in different *boroughs*.

```{r}
rest_inspec %>% 
  select(boro, score, cuisine_description) %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  filter(boro != "Missing") %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2") %>% 
  layout(
    title = "Distribution of Scores in Different Boro",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Score")
  )
```

